name: C++ CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ lcov libgtest-dev libssl-dev

      - name: Build GTest
        run: |
          cd /usr/src/gtest
          sudo cmake .
          sudo make
          sudo cp lib/*.a /usr/lib

      - name: Build
        run: ./scripts/build_cpp.sh

      - name: Run C++ Unit Tests
        run: |
          cd cpp/build
          ./runTests --gtest_color=yes

      - name: Run Bridge Tests Specifically
        run: |
          cd cpp/build
          ./runTests --gtest_filter="CBridgeTest.*" --gtest_color=yes

      - name: Generate Coverage
        run: ./scripts/generate_cpp_coverage.sh
